export { default as x } from '~icons/outline/x.svg'
export { default as check } from '~icons/outline/check.svg'
export { default as point } from '~icons/outline/point.svg'
export { default as circle } from '~icons/outline/circle.svg'
export { default as dotsVert } from '~icons/outline/dots-vertical.svg'

export { default as circleX } from '~icons/filled/circle-x.svg'
export { default as circleCheck } from '~icons/filled/circle-check.svg'
export { default as circleAlert } from '~icons/filled/alert-circle.svg'
export { default as triangleAlert } from '~icons/filled/alert-triangle.svg'
export { default as circleQuestion } from '~icons/filled/help-circle.svg'

export { default as file } from '~icons/outline/file.svg'
export { default as folder } from '~icons/outline/folder.svg'
export { default as folderOpen } from '~icons/outline/folder-open.svg'

export { default as chevronUp } from '~icons/outline/chevron-up.svg'
export { default as chevronDown } from '~icons/outline/chevron-down.svg'
export { default as chevronLeft } from '~icons/outline/chevron-left.svg'
export { default as chevronRight } from '~icons/outline/chevron-right.svg'
